-- Beacon station catalog from 臺北捷運車站微定位系統說明_v2-1.pdf.
-- Keep this migration idempotent so it can be run by `make migrate`.

INSERT INTO stations (station_id, name_zh, line_id)
VALUES
    ('BL01', '頂埔', 'BL'),
    ('BL02', '永寧', 'BL'),
    ('BL03', '土城', 'BL'),
    ('BL04', '海山', 'BL'),
    ('BL05', '亞東醫院', 'BL'),
    ('BL06', '府中', 'BL'),
    ('BL07', '板橋', 'BL'),
    ('BL08', '新埔', 'BL'),
    ('BL09', '江子翠', 'BL'),
    ('BL10', '龍山寺', 'BL'),
    ('BL11', '西門', 'BL'),
    ('BL12', '台北車站', 'BL'),
    ('BL13', '善導寺', 'BL'),
    ('BL14', '忠孝新生', 'BL'),
    ('BL15', '忠孝復興', 'BL'),
    ('BL16', '忠孝敦化', 'BL'),
    ('BL17', '國父紀念館', 'BL'),
    ('BL18', '市政府', 'BL'),
    ('BL19', '永春', 'BL'),
    ('BL20', '後山埤', 'BL'),
    ('BL21', '昆陽', 'BL'),
    ('BL22', '南港', 'BL'),
    ('BL23', '南港展覽館', 'BL'),
    ('BR01', '動物園', 'BR'),
    ('BR02', '木柵', 'BR'),
    ('BR03', '萬芳社區', 'BR'),
    ('BR04', '萬芳醫院', 'BR'),
    ('BR05', '辛亥', 'BR'),
    ('BR06', '麟光', 'BR'),
    ('BR07', '六張犁', 'BR'),
    ('BR08', '科技大樓', 'BR'),
    ('BR09', '大安', 'BR'),
    ('BR10', '忠孝復興', 'BR'),
    ('BR11', '南京復興', 'BR'),
    ('BR12', '中山國中', 'BR'),
    ('BR13', '松山機場', 'BR'),
    ('BR14', '大直', 'BR'),
    ('BR15', '劍南路', 'BR'),
    ('BR16', '西湖', 'BR'),
    ('BR17', '港墘', 'BR'),
    ('BR18', '文德', 'BR'),
    ('BR19', '內湖', 'BR'),
    ('BR20', '大湖公園', 'BR'),
    ('BR21', '葫洲', 'BR'),
    ('BR22', '東湖', 'BR'),
    ('BR23', '南港軟體園區', 'BR'),
    ('BR24', '南港展覽館', 'BR'),
    ('G01', '新店', 'G'),
    ('G02', '新店區公所', 'G'),
    ('G03', '七張', 'G'),
    ('G03A', '小碧潭', 'G'),
    ('G04', '大坪林', 'G'),
    ('G05', '景美', 'G'),
    ('G06', '萬隆', 'G'),
    ('G07', '公館', 'G'),
    ('G08', '台電大樓', 'G'),
    ('G09', '古亭', 'G'),
    ('G10', '中正紀念堂', 'G'),
    ('G11', '小南門', 'G'),
    ('G12', '西門', 'G'),
    ('G13', '北門', 'G'),
    ('G14', '中山', 'G'),
    ('G15', '松江南京', 'G'),
    ('G16', '南京復興', 'G'),
    ('G17', '台北小巨蛋', 'G'),
    ('G18', '南京三民', 'G'),
    ('G19', '松山', 'G'),
    ('O01', '南勢角', 'O'),
    ('O02', '景安', 'O'),
    ('O03', '永安市場', 'O'),
    ('O04', '頂溪', 'O'),
    ('O05', '古亭', 'O'),
    ('O06', '東門', 'O'),
    ('O07', '忠孝新生', 'O'),
    ('O08', '松江南京', 'O'),
    ('O09', '行天宮', 'O'),
    ('O10', '中山國小', 'O'),
    ('O11', '民權西路', 'O'),
    ('O12', '大橋頭', 'O'),
    ('O13', '台北橋', 'O'),
    ('O14', '菜寮', 'O'),
    ('O15', '三重', 'O'),
    ('O16', '先嗇宮', 'O'),
    ('O17', '頭前庄', 'O'),
    ('O18', '新莊', 'O'),
    ('O19', '輔大', 'O'),
    ('O20', '丹鳳', 'O'),
    ('O21', '迴龍', 'O'),
    ('O50', '三重國小', 'O'),
    ('O51', '三和國中', 'O'),
    ('O52', '徐匯中學', 'O'),
    ('O53', '三民高中', 'O'),
    ('O54', '蘆洲', 'O'),
    ('R01', '廣慈／奉天宮', 'R'),
    ('R02', '象山', 'R'),
    ('R03', '台北101／世貿', 'R'),
    ('R04', '信義安和', 'R'),
    ('R05', '大安', 'R'),
    ('R06', '大安森林公園', 'R'),
    ('R07', '東門', 'R'),
    ('R08', '中正紀念堂', 'R'),
    ('R09', '台大醫院', 'R'),
    ('R10', '台北車站', 'R'),
    ('R11', '中山', 'R'),
    ('R12', '雙連', 'R'),
    ('R13', '民權西路', 'R'),
    ('R14', '圓山', 'R'),
    ('R15', '劍潭', 'R'),
    ('R16', '士林', 'R'),
    ('R17', '芝山', 'R'),
    ('R18', '明德', 'R'),
    ('R19', '石牌', 'R'),
    ('R20', '唭哩岸', 'R'),
    ('R21', '奇岩', 'R'),
    ('R22', '北投', 'R'),
    ('R22A', '新北投', 'R'),
    ('R23', '復興崗', 'R'),
    ('R24', '忠義', 'R'),
    ('R25', '關渡', 'R'),
    ('R26', '竹圍', 'R'),
    ('R27', '紅樹林', 'R'),
    ('R28', '淡水', 'R')
ON CONFLICT (station_id) DO UPDATE
SET name_zh = EXCLUDED.name_zh,
    line_id = EXCLUDED.line_id;

-- One coffee and one lunch offer per catalog station keeps every Beacon-resolved
-- station recommendable without pretending that every physical Beacon is a shop.
INSERT INTO offers (
    offer_id, merchant_id, station_id, title, description, points_cost,
    starts_at, ends_at, category, content_version, is_active, updated_at
)
SELECT
    'offer-beacon-' || lower(station.station_id) || '-' || offer.kind,
    'merchant-beacon-catalog',
    station.station_id,
    station.name_zh || offer.title_suffix,
    station.name_zh || offer.description_suffix,
    offer.points_cost,
    now() - interval '1 day',
    now() + interval '90 days',
    offer.kind,
    1,
    true,
    now()
FROM stations AS station
CROSS JOIN (
    VALUES
        ('coffee', '周邊咖啡折抵 50 元', '周邊合作咖啡店折抵優惠。', 80),
        ('lunch', '周邊午餐折抵 80 元', '周邊合作餐飲店午餐折抵優惠。', 120)
) AS offer(kind, title_suffix, description_suffix, points_cost)
WHERE station.line_id IN ('BL', 'BR', 'G', 'O', 'R')
ON CONFLICT (offer_id) DO UPDATE
SET station_id = EXCLUDED.station_id,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    points_cost = EXCLUDED.points_cost,
    category = EXCLUDED.category,
    is_active = EXCLUDED.is_active,
    ends_at = EXCLUDED.ends_at,
    updated_at = now();

INSERT INTO inventory (offer_id, available_quantity)
SELECT offer_id, 25
FROM offers
WHERE offer_id LIKE 'offer-beacon-%'
ON CONFLICT (offer_id) DO UPDATE
SET available_quantity = GREATEST(inventory.available_quantity, EXCLUDED.available_quantity),
    updated_at = now();
