// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestContext is carried by future internal RPC requests. It contains only
// correlation identifiers and must never include a raw user identifier.
type RequestContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	JourneyId     string                 `protobuf:"bytes,3,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_api_proto_spacetime_node_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestContext) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

var File_api_proto_spacetime_node_v1_common_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_common_proto_rawDesc = "" +
	"\n" +
	"(api/proto/spacetime_node/v1/common.proto\x12\x11spacetime_node.v1\"i\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x03 \x01(\tR\tjourneyIdB/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_common_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_common_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_common_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_common_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_common_proto_rawDesc), len(file_api_proto_spacetime_node_v1_common_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_common_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_spacetime_node_v1_common_proto_goTypes = []any{
	(*RequestContext)(nil), // 0: spacetime_node.v1.RequestContext
}
var file_api_proto_spacetime_node_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_common_proto_init() }
func file_api_proto_spacetime_node_v1_common_proto_init() {
	if File_api_proto_spacetime_node_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_common_proto_rawDesc), len(file_api_proto_spacetime_node_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_common_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_common_proto_depIdxs,
		MessageInfos:      file_api_proto_spacetime_node_v1_common_proto_msgTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_common_proto = out.File
	file_api_proto_spacetime_node_v1_common_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_common_proto_depIdxs = nil
}
