// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/errors.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v3/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason is the stable, client-visible failure vocabulary for the MVP.
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	ErrorReason_INVALID_REQUEST          ErrorReason = 1
	ErrorReason_JOURNEY_NOT_FOUND        ErrorReason = 2
	ErrorReason_RECOMMENDATION_NOT_FOUND ErrorReason = 3
	ErrorReason_REDEMPTION_NOT_FOUND     ErrorReason = 4
	ErrorReason_IDEMPOTENCY_KEY_CONFLICT ErrorReason = 5
	ErrorReason_INSUFFICIENT_POINTS      ErrorReason = 6
	ErrorReason_OFFER_UNAVAILABLE        ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNSPECIFIED",
		1: "INVALID_REQUEST",
		2: "JOURNEY_NOT_FOUND",
		3: "RECOMMENDATION_NOT_FOUND",
		4: "REDEMPTION_NOT_FOUND",
		5: "IDEMPOTENCY_KEY_CONFLICT",
		6: "INSUFFICIENT_POINTS",
		7: "OFFER_UNAVAILABLE",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"INVALID_REQUEST":          1,
		"JOURNEY_NOT_FOUND":        2,
		"RECOMMENDATION_NOT_FOUND": 3,
		"REDEMPTION_NOT_FOUND":     4,
		"IDEMPOTENCY_KEY_CONFLICT": 5,
		"INSUFFICIENT_POINTS":      6,
		"OFFER_UNAVAILABLE":        7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_spacetime_node_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_proto_spacetime_node_v1_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_api_proto_spacetime_node_v1_errors_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_errors_proto_rawDesc = "" +
	"\n" +
	"(api/proto/spacetime_node/v1/errors.proto\x12\x11spacetime_node.v1\x1a\x13errors/errors.proto*\x87\x02\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x0fINVALID_REQUEST\x10\x01\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11JOURNEY_NOT_FOUND\x10\x02\x1a\x04\xa8E\x94\x03\x12\"\n" +
	"\x18RECOMMENDATION_NOT_FOUND\x10\x03\x1a\x04\xa8E\x94\x03\x12\x1e\n" +
	"\x14REDEMPTION_NOT_FOUND\x10\x04\x1a\x04\xa8E\x94\x03\x12\"\n" +
	"\x18IDEMPOTENCY_KEY_CONFLICT\x10\x05\x1a\x04\xa8E\x99\x03\x12\x1d\n" +
	"\x13INSUFFICIENT_POINTS\x10\x06\x1a\x04\xa8E\x99\x03\x12\x1b\n" +
	"\x11OFFER_UNAVAILABLE\x10\a\x1a\x04\xa8E\x99\x03B/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_errors_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_errors_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_errors_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_errors_proto_rawDesc), len(file_api_proto_spacetime_node_v1_errors_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_errors_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_spacetime_node_v1_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: spacetime_node.v1.ErrorReason
}
var file_api_proto_spacetime_node_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_errors_proto_init() }
func file_api_proto_spacetime_node_v1_errors_proto_init() {
	if File_api_proto_spacetime_node_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_errors_proto_rawDesc), len(file_api_proto_spacetime_node_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_errors_proto_depIdxs,
		EnumInfos:         file_api_proto_spacetime_node_v1_errors_proto_enumTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_errors_proto = out.File
	file_api_proto_spacetime_node_v1_errors_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_errors_proto_depIdxs = nil
}
