// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsJourneyNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_JOURNEY_NOT_FOUND.String() && e.Code == 404
}

func ErrorJourneyNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_JOURNEY_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsRecommendationNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RECOMMENDATION_NOT_FOUND.String() && e.Code == 404
}

func ErrorRecommendationNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_RECOMMENDATION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsRedemptionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REDEMPTION_NOT_FOUND.String() && e.Code == 404
}

func ErrorRedemptionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_REDEMPTION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsIdempotencyKeyConflict(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDEMPOTENCY_KEY_CONFLICT.String() && e.Code == 409
}

func ErrorIdempotencyKeyConflict(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_IDEMPOTENCY_KEY_CONFLICT.String(), fmt.Sprintf(format, args...))
}

func IsInsufficientPoints(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INSUFFICIENT_POINTS.String() && e.Code == 409
}

func ErrorInsufficientPoints(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_INSUFFICIENT_POINTS.String(), fmt.Sprintf(format, args...))
}

func IsOfferUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OFFER_UNAVAILABLE.String() && e.Code == 409
}

func ErrorOfferUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_OFFER_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}

func IsMerchantVerificationFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MERCHANT_VERIFICATION_FAILED.String() && e.Code == 409
}

func ErrorMerchantVerificationFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_MERCHANT_VERIFICATION_FAILED.String(), fmt.Sprintf(format, args...))
}
