// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/journey.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JourneyService_CreateEntryEvent_FullMethodName        = "/spacetime_node.v1.JourneyService/CreateEntryEvent"
	JourneyService_GetLatestRecommendation_FullMethodName = "/spacetime_node.v1.JourneyService/GetLatestRecommendation"
)

// JourneyServiceClient is the client API for JourneyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JourneyServiceClient interface {
	// CreateEntryEvent starts the demo journey and asynchronously triggers recommendation.
	CreateEntryEvent(ctx context.Context, in *CreateEntryEventRequest, opts ...grpc.CallOption) (*CreateEntryEventResponse, error)
	// GetLatestRecommendation returns the latest recommendation for a journey.
	GetLatestRecommendation(ctx context.Context, in *GetLatestRecommendationRequest, opts ...grpc.CallOption) (*GetLatestRecommendationResponse, error)
}

type journeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJourneyServiceClient(cc grpc.ClientConnInterface) JourneyServiceClient {
	return &journeyServiceClient{cc}
}

func (c *journeyServiceClient) CreateEntryEvent(ctx context.Context, in *CreateEntryEventRequest, opts ...grpc.CallOption) (*CreateEntryEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEntryEventResponse)
	err := c.cc.Invoke(ctx, JourneyService_CreateEntryEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journeyServiceClient) GetLatestRecommendation(ctx context.Context, in *GetLatestRecommendationRequest, opts ...grpc.CallOption) (*GetLatestRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestRecommendationResponse)
	err := c.cc.Invoke(ctx, JourneyService_GetLatestRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JourneyServiceServer is the server API for JourneyService service.
// All implementations must embed UnimplementedJourneyServiceServer
// for forward compatibility.
type JourneyServiceServer interface {
	// CreateEntryEvent starts the demo journey and asynchronously triggers recommendation.
	CreateEntryEvent(context.Context, *CreateEntryEventRequest) (*CreateEntryEventResponse, error)
	// GetLatestRecommendation returns the latest recommendation for a journey.
	GetLatestRecommendation(context.Context, *GetLatestRecommendationRequest) (*GetLatestRecommendationResponse, error)
	mustEmbedUnimplementedJourneyServiceServer()
}

// UnimplementedJourneyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJourneyServiceServer struct{}

func (UnimplementedJourneyServiceServer) CreateEntryEvent(context.Context, *CreateEntryEventRequest) (*CreateEntryEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntryEvent not implemented")
}
func (UnimplementedJourneyServiceServer) GetLatestRecommendation(context.Context, *GetLatestRecommendationRequest) (*GetLatestRecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRecommendation not implemented")
}
func (UnimplementedJourneyServiceServer) mustEmbedUnimplementedJourneyServiceServer() {}
func (UnimplementedJourneyServiceServer) testEmbeddedByValue()                        {}

// UnsafeJourneyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JourneyServiceServer will
// result in compilation errors.
type UnsafeJourneyServiceServer interface {
	mustEmbedUnimplementedJourneyServiceServer()
}

func RegisterJourneyServiceServer(s grpc.ServiceRegistrar, srv JourneyServiceServer) {
	// If the following call pancis, it indicates UnimplementedJourneyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JourneyService_ServiceDesc, srv)
}

func _JourneyService_CreateEntryEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntryEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JourneyServiceServer).CreateEntryEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JourneyService_CreateEntryEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JourneyServiceServer).CreateEntryEvent(ctx, req.(*CreateEntryEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JourneyService_GetLatestRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JourneyServiceServer).GetLatestRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JourneyService_GetLatestRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JourneyServiceServer).GetLatestRecommendation(ctx, req.(*GetLatestRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JourneyService_ServiceDesc is the grpc.ServiceDesc for JourneyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JourneyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spacetime_node.v1.JourneyService",
	HandlerType: (*JourneyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntryEvent",
			Handler:    _JourneyService_CreateEntryEvent_Handler,
		},
		{
			MethodName: "GetLatestRecommendation",
			Handler:    _JourneyService_GetLatestRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/spacetime_node/v1/journey.proto",
}
