// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/journey.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEntryEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	UserIdHash     string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	StationId      string                 `protobuf:"bytes,3,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	LineId         string                 `protobuf:"bytes,4,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	PositionId     string                 `protobuf:"bytes,5,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEntryEventRequest) Reset() {
	*x = CreateEntryEventRequest{}
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryEventRequest) ProtoMessage() {}

func (x *CreateEntryEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_journey_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEntryEventRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *CreateEntryEventRequest) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *CreateEntryEventRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *CreateEntryEventRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *CreateEntryEventRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

type CreateEntryEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JourneyId     string                 `protobuf:"bytes,1,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryEventResponse) Reset() {
	*x = CreateEntryEventResponse{}
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryEventResponse) ProtoMessage() {}

func (x *CreateEntryEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEntryEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_journey_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntryEventResponse) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

type GetLatestRecommendationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	JourneyId      string                 `protobuf:"bytes,2,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLatestRecommendationRequest) Reset() {
	*x = GetLatestRecommendationRequest{}
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRecommendationRequest) ProtoMessage() {}

func (x *GetLatestRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRecommendationRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_journey_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestRecommendationRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetLatestRecommendationRequest) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

type GetLatestRecommendationResponse struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	RecommendationId  string                     `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	JourneyId         string                     `protobuf:"bytes,2,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	OfferId           string                     `protobuf:"bytes,3,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Title             string                     `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body              string                     `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Reasons           []string                   `protobuf:"bytes,6,rep,name=reasons,proto3" json:"reasons,omitempty"`
	CopySource        string                     `protobuf:"bytes,7,opt,name=copy_source,json=copySource,proto3" json:"copy_source,omitempty"`
	DecisionLatencyMs int64                      `protobuf:"varint,8,opt,name=decision_latency_ms,json=decisionLatencyMs,proto3" json:"decision_latency_ms,omitempty"`
	Candidates        []*RecommendationCandidate `protobuf:"bytes,9,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLatestRecommendationResponse) Reset() {
	*x = GetLatestRecommendationResponse{}
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRecommendationResponse) ProtoMessage() {}

func (x *GetLatestRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRecommendationResponse.ProtoReflect.Descriptor instead.
func (*GetLatestRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_journey_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestRecommendationResponse) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *GetLatestRecommendationResponse) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

func (x *GetLatestRecommendationResponse) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *GetLatestRecommendationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetLatestRecommendationResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *GetLatestRecommendationResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *GetLatestRecommendationResponse) GetCopySource() string {
	if x != nil {
		return x.CopySource
	}
	return ""
}

func (x *GetLatestRecommendationResponse) GetDecisionLatencyMs() int64 {
	if x != nil {
		return x.DecisionLatencyMs
	}
	return 0
}

func (x *GetLatestRecommendationResponse) GetCandidates() []*RecommendationCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// RecommendationCandidate exposes the explainable boundary between vector recall and rule validation.
type RecommendationCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	VectorScore   float64                `protobuf:"fixed64,2,opt,name=vector_score,json=vectorScore,proto3" json:"vector_score,omitempty"`
	RuleScore     float64                `protobuf:"fixed64,3,opt,name=rule_score,json=ruleScore,proto3" json:"rule_score,omitempty"`
	Eligible      bool                   `protobuf:"varint,4,opt,name=eligible,proto3" json:"eligible,omitempty"`
	Reasons       []string               `protobuf:"bytes,5,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationCandidate) Reset() {
	*x = RecommendationCandidate{}
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationCandidate) ProtoMessage() {}

func (x *RecommendationCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_journey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationCandidate.ProtoReflect.Descriptor instead.
func (*RecommendationCandidate) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_journey_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendationCandidate) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *RecommendationCandidate) GetVectorScore() float64 {
	if x != nil {
		return x.VectorScore
	}
	return 0
}

func (x *RecommendationCandidate) GetRuleScore() float64 {
	if x != nil {
		return x.RuleScore
	}
	return 0
}

func (x *RecommendationCandidate) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *RecommendationCandidate) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

var File_api_proto_spacetime_node_v1_journey_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_journey_proto_rawDesc = "" +
	"\n" +
	")api/proto/spacetime_node/v1/journey.proto\x12\x11spacetime_node.v1\x1a(api/proto/spacetime_node/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xe0\x01\n" +
	"\x17CreateEntryEventRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x12\x1d\n" +
	"\n" +
	"station_id\x18\x03 \x01(\tR\tstationId\x12\x17\n" +
	"\aline_id\x18\x04 \x01(\tR\x06lineId\x12\x1f\n" +
	"\vposition_id\x18\x05 \x01(\tR\n" +
	"positionId\"9\n" +
	"\x18CreateEntryEventResponse\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x01 \x01(\tR\tjourneyId\"\x8b\x01\n" +
	"\x1eGetLatestRecommendationRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x02 \x01(\tR\tjourneyId\"\xe9\x02\n" +
	"\x1fGetLatestRecommendationResponse\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x02 \x01(\tR\tjourneyId\x12\x19\n" +
	"\boffer_id\x18\x03 \x01(\tR\aofferId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x18\n" +
	"\areasons\x18\x06 \x03(\tR\areasons\x12\x1f\n" +
	"\vcopy_source\x18\a \x01(\tR\n" +
	"copySource\x12.\n" +
	"\x13decision_latency_ms\x18\b \x01(\x03R\x11decisionLatencyMs\x12J\n" +
	"\n" +
	"candidates\x18\t \x03(\v2*.spacetime_node.v1.RecommendationCandidateR\n" +
	"candidates\"\xac\x01\n" +
	"\x17RecommendationCandidate\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12!\n" +
	"\fvector_score\x18\x02 \x01(\x01R\vvectorScore\x12\x1d\n" +
	"\n" +
	"rule_score\x18\x03 \x01(\x01R\truleScore\x12\x1a\n" +
	"\beligible\x18\x04 \x01(\bR\beligible\x12\x18\n" +
	"\areasons\x18\x05 \x03(\tR\areasons2\xc2\x02\n" +
	"\x0eJourneyService\x12\x88\x01\n" +
	"\x10CreateEntryEvent\x12*.spacetime_node.v1.CreateEntryEventRequest\x1a+.spacetime_node.v1.CreateEntryEventResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/entry-events\x12\xa4\x01\n" +
	"\x17GetLatestRecommendation\x121.spacetime_node.v1.GetLatestRecommendationRequest\x1a2.spacetime_node.v1.GetLatestRecommendationResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/recommendations/latestB/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_journey_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_journey_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_journey_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_journey_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_journey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_journey_proto_rawDesc), len(file_api_proto_spacetime_node_v1_journey_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_journey_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_journey_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_spacetime_node_v1_journey_proto_goTypes = []any{
	(*CreateEntryEventRequest)(nil),         // 0: spacetime_node.v1.CreateEntryEventRequest
	(*CreateEntryEventResponse)(nil),        // 1: spacetime_node.v1.CreateEntryEventResponse
	(*GetLatestRecommendationRequest)(nil),  // 2: spacetime_node.v1.GetLatestRecommendationRequest
	(*GetLatestRecommendationResponse)(nil), // 3: spacetime_node.v1.GetLatestRecommendationResponse
	(*RecommendationCandidate)(nil),         // 4: spacetime_node.v1.RecommendationCandidate
	(*RequestContext)(nil),                  // 5: spacetime_node.v1.RequestContext
}
var file_api_proto_spacetime_node_v1_journey_proto_depIdxs = []int32{
	5, // 0: spacetime_node.v1.CreateEntryEventRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	5, // 1: spacetime_node.v1.GetLatestRecommendationRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	4, // 2: spacetime_node.v1.GetLatestRecommendationResponse.candidates:type_name -> spacetime_node.v1.RecommendationCandidate
	0, // 3: spacetime_node.v1.JourneyService.CreateEntryEvent:input_type -> spacetime_node.v1.CreateEntryEventRequest
	2, // 4: spacetime_node.v1.JourneyService.GetLatestRecommendation:input_type -> spacetime_node.v1.GetLatestRecommendationRequest
	1, // 5: spacetime_node.v1.JourneyService.CreateEntryEvent:output_type -> spacetime_node.v1.CreateEntryEventResponse
	3, // 6: spacetime_node.v1.JourneyService.GetLatestRecommendation:output_type -> spacetime_node.v1.GetLatestRecommendationResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_journey_proto_init() }
func file_api_proto_spacetime_node_v1_journey_proto_init() {
	if File_api_proto_spacetime_node_v1_journey_proto != nil {
		return
	}
	file_api_proto_spacetime_node_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_journey_proto_rawDesc), len(file_api_proto_spacetime_node_v1_journey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_journey_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_journey_proto_depIdxs,
		MessageInfos:      file_api_proto_spacetime_node_v1_journey_proto_msgTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_journey_proto = out.File
	file_api_proto_spacetime_node_v1_journey_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_journey_proto_depIdxs = nil
}
