// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/journey.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationJourneyServiceCreateEntryEvent = "/spacetime_node.v1.JourneyService/CreateEntryEvent"
const OperationJourneyServiceGetLatestRecommendation = "/spacetime_node.v1.JourneyService/GetLatestRecommendation"

type JourneyServiceHTTPServer interface {
	// CreateEntryEvent CreateEntryEvent starts the demo journey and asynchronously triggers recommendation.
	CreateEntryEvent(context.Context, *CreateEntryEventRequest) (*CreateEntryEventResponse, error)
	// GetLatestRecommendation GetLatestRecommendation returns the latest recommendation for a journey.
	GetLatestRecommendation(context.Context, *GetLatestRecommendationRequest) (*GetLatestRecommendationResponse, error)
}

func RegisterJourneyServiceHTTPServer(s *http.Server, srv JourneyServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/entry-events", _JourneyService_CreateEntryEvent0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/recommendations/latest", _JourneyService_GetLatestRecommendation0_HTTP_Handler(srv))
}

func _JourneyService_CreateEntryEvent0_HTTP_Handler(srv JourneyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEntryEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJourneyServiceCreateEntryEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEntryEvent(ctx, req.(*CreateEntryEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEntryEventResponse)
		return ctx.Result(200, reply)
	}
}

func _JourneyService_GetLatestRecommendation0_HTTP_Handler(srv JourneyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLatestRecommendationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJourneyServiceGetLatestRecommendation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLatestRecommendation(ctx, req.(*GetLatestRecommendationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLatestRecommendationResponse)
		return ctx.Result(200, reply)
	}
}

type JourneyServiceHTTPClient interface {
	// CreateEntryEvent CreateEntryEvent starts the demo journey and asynchronously triggers recommendation.
	CreateEntryEvent(ctx context.Context, req *CreateEntryEventRequest, opts ...http.CallOption) (rsp *CreateEntryEventResponse, err error)
	// GetLatestRecommendation GetLatestRecommendation returns the latest recommendation for a journey.
	GetLatestRecommendation(ctx context.Context, req *GetLatestRecommendationRequest, opts ...http.CallOption) (rsp *GetLatestRecommendationResponse, err error)
}

type JourneyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewJourneyServiceHTTPClient(client *http.Client) JourneyServiceHTTPClient {
	return &JourneyServiceHTTPClientImpl{client}
}

// CreateEntryEvent CreateEntryEvent starts the demo journey and asynchronously triggers recommendation.
func (c *JourneyServiceHTTPClientImpl) CreateEntryEvent(ctx context.Context, in *CreateEntryEventRequest, opts ...http.CallOption) (*CreateEntryEventResponse, error) {
	var out CreateEntryEventResponse
	pattern := "/v1/entry-events"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationJourneyServiceCreateEntryEvent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLatestRecommendation GetLatestRecommendation returns the latest recommendation for a journey.
func (c *JourneyServiceHTTPClientImpl) GetLatestRecommendation(ctx context.Context, in *GetLatestRecommendationRequest, opts ...http.CallOption) (*GetLatestRecommendationResponse, error) {
	var out GetLatestRecommendationResponse
	pattern := "/v1/recommendations/latest"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationJourneyServiceGetLatestRecommendation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
