// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/mobility.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MobilityService_ResolveBeacon_FullMethodName = "/spacetime_node.v1.MobilityService/ResolveBeacon"
)

// MobilityServiceClient is the client API for MobilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MobilityServiceClient interface {
	// ResolveBeacon normalizes a Beacon observation without exposing provider credentials.
	ResolveBeacon(ctx context.Context, in *ResolveBeaconRequest, opts ...grpc.CallOption) (*ResolveBeaconResponse, error)
}

type mobilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMobilityServiceClient(cc grpc.ClientConnInterface) MobilityServiceClient {
	return &mobilityServiceClient{cc}
}

func (c *mobilityServiceClient) ResolveBeacon(ctx context.Context, in *ResolveBeaconRequest, opts ...grpc.CallOption) (*ResolveBeaconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveBeaconResponse)
	err := c.cc.Invoke(ctx, MobilityService_ResolveBeacon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobilityServiceServer is the server API for MobilityService service.
// All implementations must embed UnimplementedMobilityServiceServer
// for forward compatibility.
type MobilityServiceServer interface {
	// ResolveBeacon normalizes a Beacon observation without exposing provider credentials.
	ResolveBeacon(context.Context, *ResolveBeaconRequest) (*ResolveBeaconResponse, error)
	mustEmbedUnimplementedMobilityServiceServer()
}

// UnimplementedMobilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMobilityServiceServer struct{}

func (UnimplementedMobilityServiceServer) ResolveBeacon(context.Context, *ResolveBeaconRequest) (*ResolveBeaconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveBeacon not implemented")
}
func (UnimplementedMobilityServiceServer) mustEmbedUnimplementedMobilityServiceServer() {}
func (UnimplementedMobilityServiceServer) testEmbeddedByValue()                         {}

// UnsafeMobilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MobilityServiceServer will
// result in compilation errors.
type UnsafeMobilityServiceServer interface {
	mustEmbedUnimplementedMobilityServiceServer()
}

func RegisterMobilityServiceServer(s grpc.ServiceRegistrar, srv MobilityServiceServer) {
	// If the following call pancis, it indicates UnimplementedMobilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MobilityService_ServiceDesc, srv)
}

func _MobilityService_ResolveBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobilityServiceServer).ResolveBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MobilityService_ResolveBeacon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobilityServiceServer).ResolveBeacon(ctx, req.(*ResolveBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MobilityService_ServiceDesc is the grpc.ServiceDesc for MobilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MobilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spacetime_node.v1.MobilityService",
	HandlerType: (*MobilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveBeacon",
			Handler:    _MobilityService_ResolveBeacon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/spacetime_node/v1/mobility.proto",
}
