// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/mobility.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationMobilityServiceResolveBeacon = "/spacetime_node.v1.MobilityService/ResolveBeacon"

type MobilityServiceHTTPServer interface {
	// ResolveBeacon ResolveBeacon normalizes a Beacon observation without exposing provider credentials.
	ResolveBeacon(context.Context, *ResolveBeaconRequest) (*ResolveBeaconResponse, error)
}

func RegisterMobilityServiceHTTPServer(s *http.Server, srv MobilityServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/mobility/beacon/resolve", _MobilityService_ResolveBeacon0_HTTP_Handler(srv))
}

func _MobilityService_ResolveBeacon0_HTTP_Handler(srv MobilityServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveBeaconRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMobilityServiceResolveBeacon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveBeacon(ctx, req.(*ResolveBeaconRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResolveBeaconResponse)
		return ctx.Result(200, reply)
	}
}

type MobilityServiceHTTPClient interface {
	// ResolveBeacon ResolveBeacon normalizes a Beacon observation without exposing provider credentials.
	ResolveBeacon(ctx context.Context, req *ResolveBeaconRequest, opts ...http.CallOption) (rsp *ResolveBeaconResponse, err error)
}

type MobilityServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMobilityServiceHTTPClient(client *http.Client) MobilityServiceHTTPClient {
	return &MobilityServiceHTTPClientImpl{client}
}

// ResolveBeacon ResolveBeacon normalizes a Beacon observation without exposing provider credentials.
func (c *MobilityServiceHTTPClientImpl) ResolveBeacon(ctx context.Context, in *ResolveBeaconRequest, opts ...http.CallOption) (*ResolveBeaconResponse, error) {
	var out ResolveBeaconResponse
	pattern := "/v1/mobility/beacon/resolve"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMobilityServiceResolveBeacon),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
