// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/mobility.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveBeaconRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Major          int64                  `protobuf:"varint,3,opt,name=major,proto3" json:"major,omitempty"`
	Minor          int64                  `protobuf:"varint,4,opt,name=minor,proto3" json:"minor,omitempty"`
	Power          int32                  `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveBeaconRequest) Reset() {
	*x = ResolveBeaconRequest{}
	mi := &file_api_proto_spacetime_node_v1_mobility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBeaconRequest) ProtoMessage() {}

func (x *ResolveBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_mobility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBeaconRequest.ProtoReflect.Descriptor instead.
func (*ResolveBeaconRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_mobility_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveBeaconRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *ResolveBeaconRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ResolveBeaconRequest) GetMajor() int64 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ResolveBeaconRequest) GetMinor() int64 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *ResolveBeaconRequest) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

type ResolveBeaconResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *BeaconContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBeaconResponse) Reset() {
	*x = ResolveBeaconResponse{}
	mi := &file_api_proto_spacetime_node_v1_mobility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBeaconResponse) ProtoMessage() {}

func (x *ResolveBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_mobility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBeaconResponse.ProtoReflect.Descriptor instead.
func (*ResolveBeaconResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_mobility_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveBeaconResponse) GetContext() *BeaconContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type BeaconContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	LineId        string                 `protobuf:"bytes,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	PositionId    string                 `protobuf:"bytes,3,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	StationName   string                 `protobuf:"bytes,4,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	NearExit      bool                   `protobuf:"varint,7,opt,name=near_exit,json=nearExit,proto3" json:"near_exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconContext) Reset() {
	*x = BeaconContext{}
	mi := &file_api_proto_spacetime_node_v1_mobility_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconContext) ProtoMessage() {}

func (x *BeaconContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_mobility_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconContext.ProtoReflect.Descriptor instead.
func (*BeaconContext) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_mobility_proto_rawDescGZIP(), []int{2}
}

func (x *BeaconContext) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *BeaconContext) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *BeaconContext) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *BeaconContext) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *BeaconContext) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BeaconContext) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *BeaconContext) GetNearExit() bool {
	if x != nil {
		return x.NearExit
	}
	return false
}

var File_api_proto_spacetime_node_v1_mobility_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_mobility_proto_rawDesc = "" +
	"\n" +
	"*api/proto/spacetime_node/v1/mobility.proto\x12\x11spacetime_node.v1\x1a(api/proto/spacetime_node/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xb8\x01\n" +
	"\x14ResolveBeaconRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05major\x18\x03 \x01(\x03R\x05major\x12\x14\n" +
	"\x05minor\x18\x04 \x01(\x03R\x05minor\x12\x14\n" +
	"\x05power\x18\x05 \x01(\x05R\x05power\"S\n" +
	"\x15ResolveBeaconResponse\x12:\n" +
	"\acontext\x18\x01 \x01(\v2 .spacetime_node.v1.BeaconContextR\acontext\"\xe0\x01\n" +
	"\rBeaconContext\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x17\n" +
	"\aline_id\x18\x02 \x01(\tR\x06lineId\x12\x1f\n" +
	"\vposition_id\x18\x03 \x01(\tR\n" +
	"positionId\x12!\n" +
	"\fstation_name\x18\x04 \x01(\tR\vstationName\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12\x1b\n" +
	"\tnear_exit\x18\a \x01(\bR\bnearExit2\x9e\x01\n" +
	"\x0fMobilityService\x12\x8a\x01\n" +
	"\rResolveBeacon\x12'.spacetime_node.v1.ResolveBeaconRequest\x1a(.spacetime_node.v1.ResolveBeaconResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/mobility/beacon/resolveB/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_mobility_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_mobility_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_mobility_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_mobility_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_mobility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_mobility_proto_rawDesc), len(file_api_proto_spacetime_node_v1_mobility_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_mobility_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_mobility_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_spacetime_node_v1_mobility_proto_goTypes = []any{
	(*ResolveBeaconRequest)(nil),  // 0: spacetime_node.v1.ResolveBeaconRequest
	(*ResolveBeaconResponse)(nil), // 1: spacetime_node.v1.ResolveBeaconResponse
	(*BeaconContext)(nil),         // 2: spacetime_node.v1.BeaconContext
	(*RequestContext)(nil),        // 3: spacetime_node.v1.RequestContext
}
var file_api_proto_spacetime_node_v1_mobility_proto_depIdxs = []int32{
	3, // 0: spacetime_node.v1.ResolveBeaconRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	2, // 1: spacetime_node.v1.ResolveBeaconResponse.context:type_name -> spacetime_node.v1.BeaconContext
	0, // 2: spacetime_node.v1.MobilityService.ResolveBeacon:input_type -> spacetime_node.v1.ResolveBeaconRequest
	1, // 3: spacetime_node.v1.MobilityService.ResolveBeacon:output_type -> spacetime_node.v1.ResolveBeaconResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_mobility_proto_init() }
func file_api_proto_spacetime_node_v1_mobility_proto_init() {
	if File_api_proto_spacetime_node_v1_mobility_proto != nil {
		return
	}
	file_api_proto_spacetime_node_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_mobility_proto_rawDesc), len(file_api_proto_spacetime_node_v1_mobility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_mobility_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_mobility_proto_depIdxs,
		MessageInfos:      file_api_proto_spacetime_node_v1_mobility_proto_msgTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_mobility_proto = out.File
	file_api_proto_spacetime_node_v1_mobility_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_mobility_proto_depIdxs = nil
}
