// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/notification.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNotificationSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	UserIdHash     string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	Endpoint       string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh         string                 `protobuf:"bytes,4,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth           string                 `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	UserAgent      string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNotificationSubscriptionRequest) Reset() {
	*x = RegisterNotificationSubscriptionRequest{}
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNotificationSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNotificationSubscriptionRequest) ProtoMessage() {}

func (x *RegisterNotificationSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNotificationSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*RegisterNotificationSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNotificationSubscriptionRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *RegisterNotificationSubscriptionRequest) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *RegisterNotificationSubscriptionRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterNotificationSubscriptionRequest) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *RegisterNotificationSubscriptionRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *RegisterNotificationSubscriptionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RegisterNotificationSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Active         bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Channel        string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNotificationSubscriptionResponse) Reset() {
	*x = RegisterNotificationSubscriptionResponse{}
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNotificationSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNotificationSubscriptionResponse) ProtoMessage() {}

func (x *RegisterNotificationSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNotificationSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*RegisterNotificationSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNotificationSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RegisterNotificationSubscriptionResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RegisterNotificationSubscriptionResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type RevokeNotificationSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	UserIdHash     string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeNotificationSubscriptionRequest) Reset() {
	*x = RevokeNotificationSubscriptionRequest{}
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeNotificationSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeNotificationSubscriptionRequest) ProtoMessage() {}

func (x *RevokeNotificationSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeNotificationSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*RevokeNotificationSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeNotificationSubscriptionRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *RevokeNotificationSubscriptionRequest) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *RevokeNotificationSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type RevokeNotificationSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Active         bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeNotificationSubscriptionResponse) Reset() {
	*x = RevokeNotificationSubscriptionResponse{}
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeNotificationSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeNotificationSubscriptionResponse) ProtoMessage() {}

func (x *RevokeNotificationSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeNotificationSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*RevokeNotificationSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeNotificationSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RevokeNotificationSubscriptionResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_api_proto_spacetime_node_v1_notification_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_notification_proto_rawDesc = "" +
	"\n" +
	".api/proto/spacetime_node/v1/notification.proto\x12\x11spacetime_node.v1\x1a(api/proto/spacetime_node/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xfe\x01\n" +
	"'RegisterNotificationSubscriptionRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06p256dh\x18\x04 \x01(\tR\x06p256dh\x12\x12\n" +
	"\x04auth\x18\x05 \x01(\tR\x04auth\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\"\x85\x01\n" +
	"(RegisterNotificationSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"\xbe\x01\n" +
	"%RevokeNotificationSubscriptionRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\"i\n" +
	"&RevokeNotificationSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active2\xb0\x03\n" +
	"\x13NotificationService\x12\xc6\x01\n" +
	" RegisterNotificationSubscription\x12:.spacetime_node.v1.RegisterNotificationSubscriptionRequest\x1a;.spacetime_node.v1.RegisterNotificationSubscriptionResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/notification-subscriptions\x12\xcf\x01\n" +
	"\x1eRevokeNotificationSubscription\x128.spacetime_node.v1.RevokeNotificationSubscriptionRequest\x1a9.spacetime_node.v1.RevokeNotificationSubscriptionResponse\"8\x82\xd3\xe4\x93\x022*0/v1/notification-subscriptions/{subscription_id}B/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_notification_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_notification_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_notification_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_notification_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_notification_proto_rawDesc), len(file_api_proto_spacetime_node_v1_notification_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_notification_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_spacetime_node_v1_notification_proto_goTypes = []any{
	(*RegisterNotificationSubscriptionRequest)(nil),  // 0: spacetime_node.v1.RegisterNotificationSubscriptionRequest
	(*RegisterNotificationSubscriptionResponse)(nil), // 1: spacetime_node.v1.RegisterNotificationSubscriptionResponse
	(*RevokeNotificationSubscriptionRequest)(nil),    // 2: spacetime_node.v1.RevokeNotificationSubscriptionRequest
	(*RevokeNotificationSubscriptionResponse)(nil),   // 3: spacetime_node.v1.RevokeNotificationSubscriptionResponse
	(*RequestContext)(nil),                           // 4: spacetime_node.v1.RequestContext
}
var file_api_proto_spacetime_node_v1_notification_proto_depIdxs = []int32{
	4, // 0: spacetime_node.v1.RegisterNotificationSubscriptionRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	4, // 1: spacetime_node.v1.RevokeNotificationSubscriptionRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	0, // 2: spacetime_node.v1.NotificationService.RegisterNotificationSubscription:input_type -> spacetime_node.v1.RegisterNotificationSubscriptionRequest
	2, // 3: spacetime_node.v1.NotificationService.RevokeNotificationSubscription:input_type -> spacetime_node.v1.RevokeNotificationSubscriptionRequest
	1, // 4: spacetime_node.v1.NotificationService.RegisterNotificationSubscription:output_type -> spacetime_node.v1.RegisterNotificationSubscriptionResponse
	3, // 5: spacetime_node.v1.NotificationService.RevokeNotificationSubscription:output_type -> spacetime_node.v1.RevokeNotificationSubscriptionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_notification_proto_init() }
func file_api_proto_spacetime_node_v1_notification_proto_init() {
	if File_api_proto_spacetime_node_v1_notification_proto != nil {
		return
	}
	file_api_proto_spacetime_node_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_notification_proto_rawDesc), len(file_api_proto_spacetime_node_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_notification_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_notification_proto_depIdxs,
		MessageInfos:      file_api_proto_spacetime_node_v1_notification_proto_msgTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_notification_proto = out.File
	file_api_proto_spacetime_node_v1_notification_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_notification_proto_depIdxs = nil
}
