// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/notification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationNotificationServiceRegisterNotificationSubscription = "/spacetime_node.v1.NotificationService/RegisterNotificationSubscription"
const OperationNotificationServiceRevokeNotificationSubscription = "/spacetime_node.v1.NotificationService/RevokeNotificationSubscription"

type NotificationServiceHTTPServer interface {
	RegisterNotificationSubscription(context.Context, *RegisterNotificationSubscriptionRequest) (*RegisterNotificationSubscriptionResponse, error)
	RevokeNotificationSubscription(context.Context, *RevokeNotificationSubscriptionRequest) (*RevokeNotificationSubscriptionResponse, error)
}

func RegisterNotificationServiceHTTPServer(s *http.Server, srv NotificationServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/notification-subscriptions", _NotificationService_RegisterNotificationSubscription0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/notification-subscriptions/{subscription_id}", _NotificationService_RevokeNotificationSubscription0_HTTP_Handler(srv))
}

func _NotificationService_RegisterNotificationSubscription0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterNotificationSubscriptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceRegisterNotificationSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterNotificationSubscription(ctx, req.(*RegisterNotificationSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterNotificationSubscriptionResponse)
		return ctx.Result(200, reply)
	}
}

func _NotificationService_RevokeNotificationSubscription0_HTTP_Handler(srv NotificationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeNotificationSubscriptionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNotificationServiceRevokeNotificationSubscription)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeNotificationSubscription(ctx, req.(*RevokeNotificationSubscriptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeNotificationSubscriptionResponse)
		return ctx.Result(200, reply)
	}
}

type NotificationServiceHTTPClient interface {
	RegisterNotificationSubscription(ctx context.Context, req *RegisterNotificationSubscriptionRequest, opts ...http.CallOption) (rsp *RegisterNotificationSubscriptionResponse, err error)
	RevokeNotificationSubscription(ctx context.Context, req *RevokeNotificationSubscriptionRequest, opts ...http.CallOption) (rsp *RevokeNotificationSubscriptionResponse, err error)
}

type NotificationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNotificationServiceHTTPClient(client *http.Client) NotificationServiceHTTPClient {
	return &NotificationServiceHTTPClientImpl{client}
}

func (c *NotificationServiceHTTPClientImpl) RegisterNotificationSubscription(ctx context.Context, in *RegisterNotificationSubscriptionRequest, opts ...http.CallOption) (*RegisterNotificationSubscriptionResponse, error) {
	var out RegisterNotificationSubscriptionResponse
	pattern := "/v1/notification-subscriptions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationNotificationServiceRegisterNotificationSubscription),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *NotificationServiceHTTPClientImpl) RevokeNotificationSubscription(ctx context.Context, in *RevokeNotificationSubscriptionRequest, opts ...http.CallOption) (*RevokeNotificationSubscriptionResponse, error) {
	var out RevokeNotificationSubscriptionResponse
	pattern := "/v1/notification-subscriptions/{subscription_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationNotificationServiceRevokeNotificationSubscription),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
