// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/redemption.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedemptionService_CreateRedemption_FullMethodName = "/spacetime_node.v1.RedemptionService/CreateRedemption"
	RedemptionService_GetRedemption_FullMethodName    = "/spacetime_node.v1.RedemptionService/GetRedemption"
	RedemptionService_VerifyRedemption_FullMethodName = "/spacetime_node.v1.RedemptionService/VerifyRedemption"
)

// RedemptionServiceClient is the client API for RedemptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedemptionServiceClient interface {
	// CreateRedemption consumes points and reserves inventory exactly once per key.
	CreateRedemption(ctx context.Context, in *CreateRedemptionRequest, opts ...grpc.CallOption) (*CreateRedemptionResponse, error)
	// GetRedemption returns the persisted redemption and merchant-verification state.
	GetRedemption(ctx context.Context, in *GetRedemptionRequest, opts ...grpc.CallOption) (*GetRedemptionResponse, error)
	// VerifyRedemption is a demo merchant verification endpoint.
	VerifyRedemption(ctx context.Context, in *VerifyRedemptionRequest, opts ...grpc.CallOption) (*VerifyRedemptionResponse, error)
}

type redemptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedemptionServiceClient(cc grpc.ClientConnInterface) RedemptionServiceClient {
	return &redemptionServiceClient{cc}
}

func (c *redemptionServiceClient) CreateRedemption(ctx context.Context, in *CreateRedemptionRequest, opts ...grpc.CallOption) (*CreateRedemptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRedemptionResponse)
	err := c.cc.Invoke(ctx, RedemptionService_CreateRedemption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redemptionServiceClient) GetRedemption(ctx context.Context, in *GetRedemptionRequest, opts ...grpc.CallOption) (*GetRedemptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedemptionResponse)
	err := c.cc.Invoke(ctx, RedemptionService_GetRedemption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redemptionServiceClient) VerifyRedemption(ctx context.Context, in *VerifyRedemptionRequest, opts ...grpc.CallOption) (*VerifyRedemptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyRedemptionResponse)
	err := c.cc.Invoke(ctx, RedemptionService_VerifyRedemption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedemptionServiceServer is the server API for RedemptionService service.
// All implementations must embed UnimplementedRedemptionServiceServer
// for forward compatibility.
type RedemptionServiceServer interface {
	// CreateRedemption consumes points and reserves inventory exactly once per key.
	CreateRedemption(context.Context, *CreateRedemptionRequest) (*CreateRedemptionResponse, error)
	// GetRedemption returns the persisted redemption and merchant-verification state.
	GetRedemption(context.Context, *GetRedemptionRequest) (*GetRedemptionResponse, error)
	// VerifyRedemption is a demo merchant verification endpoint.
	VerifyRedemption(context.Context, *VerifyRedemptionRequest) (*VerifyRedemptionResponse, error)
	mustEmbedUnimplementedRedemptionServiceServer()
}

// UnimplementedRedemptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedemptionServiceServer struct{}

func (UnimplementedRedemptionServiceServer) CreateRedemption(context.Context, *CreateRedemptionRequest) (*CreateRedemptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRedemption not implemented")
}
func (UnimplementedRedemptionServiceServer) GetRedemption(context.Context, *GetRedemptionRequest) (*GetRedemptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedemption not implemented")
}
func (UnimplementedRedemptionServiceServer) VerifyRedemption(context.Context, *VerifyRedemptionRequest) (*VerifyRedemptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyRedemption not implemented")
}
func (UnimplementedRedemptionServiceServer) mustEmbedUnimplementedRedemptionServiceServer() {}
func (UnimplementedRedemptionServiceServer) testEmbeddedByValue()                           {}

// UnsafeRedemptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedemptionServiceServer will
// result in compilation errors.
type UnsafeRedemptionServiceServer interface {
	mustEmbedUnimplementedRedemptionServiceServer()
}

func RegisterRedemptionServiceServer(s grpc.ServiceRegistrar, srv RedemptionServiceServer) {
	// If the following call pancis, it indicates UnimplementedRedemptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedemptionService_ServiceDesc, srv)
}

func _RedemptionService_CreateRedemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRedemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedemptionServiceServer).CreateRedemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedemptionService_CreateRedemption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedemptionServiceServer).CreateRedemption(ctx, req.(*CreateRedemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedemptionService_GetRedemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedemptionServiceServer).GetRedemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedemptionService_GetRedemption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedemptionServiceServer).GetRedemption(ctx, req.(*GetRedemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedemptionService_VerifyRedemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRedemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedemptionServiceServer).VerifyRedemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedemptionService_VerifyRedemption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedemptionServiceServer).VerifyRedemption(ctx, req.(*VerifyRedemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedemptionService_ServiceDesc is the grpc.ServiceDesc for RedemptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedemptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spacetime_node.v1.RedemptionService",
	HandlerType: (*RedemptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRedemption",
			Handler:    _RedemptionService_CreateRedemption_Handler,
		},
		{
			MethodName: "GetRedemption",
			Handler:    _RedemptionService_GetRedemption_Handler,
		},
		{
			MethodName: "VerifyRedemption",
			Handler:    _RedemptionService_VerifyRedemption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/spacetime_node/v1/redemption.proto",
}
