// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/redemption.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedemptionStatus int32

const (
	RedemptionStatus_REDEMPTION_STATUS_UNSPECIFIED RedemptionStatus = 0
	RedemptionStatus_REDEMPTION_STATUS_PENDING     RedemptionStatus = 1
	RedemptionStatus_REDEMPTION_STATUS_SUCCEEDED   RedemptionStatus = 2
	RedemptionStatus_REDEMPTION_STATUS_REJECTED    RedemptionStatus = 3
	RedemptionStatus_REDEMPTION_STATUS_VERIFIED    RedemptionStatus = 4
)

// Enum value maps for RedemptionStatus.
var (
	RedemptionStatus_name = map[int32]string{
		0: "REDEMPTION_STATUS_UNSPECIFIED",
		1: "REDEMPTION_STATUS_PENDING",
		2: "REDEMPTION_STATUS_SUCCEEDED",
		3: "REDEMPTION_STATUS_REJECTED",
		4: "REDEMPTION_STATUS_VERIFIED",
	}
	RedemptionStatus_value = map[string]int32{
		"REDEMPTION_STATUS_UNSPECIFIED": 0,
		"REDEMPTION_STATUS_PENDING":     1,
		"REDEMPTION_STATUS_SUCCEEDED":   2,
		"REDEMPTION_STATUS_REJECTED":    3,
		"REDEMPTION_STATUS_VERIFIED":    4,
	}
)

func (x RedemptionStatus) Enum() *RedemptionStatus {
	p := new(RedemptionStatus)
	*p = x
	return p
}

func (x RedemptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RedemptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_spacetime_node_v1_redemption_proto_enumTypes[0].Descriptor()
}

func (RedemptionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_spacetime_node_v1_redemption_proto_enumTypes[0]
}

func (x RedemptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RedemptionStatus.Descriptor instead.
func (RedemptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP(), []int{0}
}

type CreateRedemptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	UserIdHash     string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	OfferId        string                 `protobuf:"bytes,3,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	// For HTTP, the adapter maps the Idempotency-Key header to this field.
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRedemptionRequest) Reset() {
	*x = CreateRedemptionRequest{}
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRedemptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedemptionRequest) ProtoMessage() {}

func (x *CreateRedemptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedemptionRequest.ProtoReflect.Descriptor instead.
func (*CreateRedemptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRedemptionRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *CreateRedemptionRequest) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *CreateRedemptionRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *CreateRedemptionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateRedemptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redemption    *Redemption            `protobuf:"bytes,1,opt,name=redemption,proto3" json:"redemption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRedemptionResponse) Reset() {
	*x = CreateRedemptionResponse{}
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRedemptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedemptionResponse) ProtoMessage() {}

func (x *CreateRedemptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedemptionResponse.ProtoReflect.Descriptor instead.
func (*CreateRedemptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRedemptionResponse) GetRedemption() *Redemption {
	if x != nil {
		return x.Redemption
	}
	return nil
}

type GetRedemptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	RedemptionId   string                 `protobuf:"bytes,2,opt,name=redemption_id,json=redemptionId,proto3" json:"redemption_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRedemptionRequest) Reset() {
	*x = GetRedemptionRequest{}
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedemptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedemptionRequest) ProtoMessage() {}

func (x *GetRedemptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedemptionRequest.ProtoReflect.Descriptor instead.
func (*GetRedemptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP(), []int{2}
}

func (x *GetRedemptionRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetRedemptionRequest) GetRedemptionId() string {
	if x != nil {
		return x.RedemptionId
	}
	return ""
}

type GetRedemptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redemption    *Redemption            `protobuf:"bytes,1,opt,name=redemption,proto3" json:"redemption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRedemptionResponse) Reset() {
	*x = GetRedemptionResponse{}
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRedemptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRedemptionResponse) ProtoMessage() {}

func (x *GetRedemptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRedemptionResponse.ProtoReflect.Descriptor instead.
func (*GetRedemptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP(), []int{3}
}

func (x *GetRedemptionResponse) GetRedemption() *Redemption {
	if x != nil {
		return x.Redemption
	}
	return nil
}

type Redemption struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RedemptionId             string                 `protobuf:"bytes,1,opt,name=redemption_id,json=redemptionId,proto3" json:"redemption_id,omitempty"`
	JourneyId                string                 `protobuf:"bytes,2,opt,name=journey_id,json=journeyId,proto3" json:"journey_id,omitempty"`
	OfferId                  string                 `protobuf:"bytes,3,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Status                   RedemptionStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=spacetime_node.v1.RedemptionStatus" json:"status,omitempty"`
	PointsCost               int64                  `protobuf:"varint,5,opt,name=points_cost,json=pointsCost,proto3" json:"points_cost,omitempty"`
	MerchantVerificationCode string                 `protobuf:"bytes,6,opt,name=merchant_verification_code,json=merchantVerificationCode,proto3" json:"merchant_verification_code,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Redemption) Reset() {
	*x = Redemption{}
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redemption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redemption) ProtoMessage() {}

func (x *Redemption) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_redemption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redemption.ProtoReflect.Descriptor instead.
func (*Redemption) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP(), []int{4}
}

func (x *Redemption) GetRedemptionId() string {
	if x != nil {
		return x.RedemptionId
	}
	return ""
}

func (x *Redemption) GetJourneyId() string {
	if x != nil {
		return x.JourneyId
	}
	return ""
}

func (x *Redemption) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Redemption) GetStatus() RedemptionStatus {
	if x != nil {
		return x.Status
	}
	return RedemptionStatus_REDEMPTION_STATUS_UNSPECIFIED
}

func (x *Redemption) GetPointsCost() int64 {
	if x != nil {
		return x.PointsCost
	}
	return 0
}

func (x *Redemption) GetMerchantVerificationCode() string {
	if x != nil {
		return x.MerchantVerificationCode
	}
	return ""
}

var File_api_proto_spacetime_node_v1_redemption_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_redemption_proto_rawDesc = "" +
	"\n" +
	",api/proto/spacetime_node/v1/redemption.proto\x12\x11spacetime_node.v1\x1a(api/proto/spacetime_node/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\xcb\x01\n" +
	"\x17CreateRedemptionRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x12\x19\n" +
	"\boffer_id\x18\x03 \x01(\tR\aofferId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"Y\n" +
	"\x18CreateRedemptionResponse\x12=\n" +
	"\n" +
	"redemption\x18\x01 \x01(\v2\x1d.spacetime_node.v1.RedemptionR\n" +
	"redemption\"\x87\x01\n" +
	"\x14GetRedemptionRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12#\n" +
	"\rredemption_id\x18\x02 \x01(\tR\fredemptionId\"V\n" +
	"\x15GetRedemptionResponse\x12=\n" +
	"\n" +
	"redemption\x18\x01 \x01(\v2\x1d.spacetime_node.v1.RedemptionR\n" +
	"redemption\"\x87\x02\n" +
	"\n" +
	"Redemption\x12#\n" +
	"\rredemption_id\x18\x01 \x01(\tR\fredemptionId\x12\x1d\n" +
	"\n" +
	"journey_id\x18\x02 \x01(\tR\tjourneyId\x12\x19\n" +
	"\boffer_id\x18\x03 \x01(\tR\aofferId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.spacetime_node.v1.RedemptionStatusR\x06status\x12\x1f\n" +
	"\vpoints_cost\x18\x05 \x01(\x03R\n" +
	"pointsCost\x12<\n" +
	"\x1amerchant_verification_code\x18\x06 \x01(\tR\x18merchantVerificationCode*\xb5\x01\n" +
	"\x10RedemptionStatus\x12!\n" +
	"\x1dREDEMPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19REDEMPTION_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bREDEMPTION_STATUS_SUCCEEDED\x10\x02\x12\x1e\n" +
	"\x1aREDEMPTION_STATUS_REJECTED\x10\x03\x12\x1e\n" +
	"\x1aREDEMPTION_STATUS_VERIFIED\x10\x042\xab\x02\n" +
	"\x11RedemptionService\x12\x87\x01\n" +
	"\x10CreateRedemption\x12*.spacetime_node.v1.CreateRedemptionRequest\x1a+.spacetime_node.v1.CreateRedemptionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/redemptions\x12\x8b\x01\n" +
	"\rGetRedemption\x12'.spacetime_node.v1.GetRedemptionRequest\x1a(.spacetime_node.v1.GetRedemptionResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/redemptions/{redemption_id}B/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_redemption_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_redemption_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_redemption_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_redemption_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_redemption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_redemption_proto_rawDesc), len(file_api_proto_spacetime_node_v1_redemption_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_redemption_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_redemption_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_spacetime_node_v1_redemption_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_spacetime_node_v1_redemption_proto_goTypes = []any{
	(RedemptionStatus)(0),            // 0: spacetime_node.v1.RedemptionStatus
	(*CreateRedemptionRequest)(nil),  // 1: spacetime_node.v1.CreateRedemptionRequest
	(*CreateRedemptionResponse)(nil), // 2: spacetime_node.v1.CreateRedemptionResponse
	(*GetRedemptionRequest)(nil),     // 3: spacetime_node.v1.GetRedemptionRequest
	(*GetRedemptionResponse)(nil),    // 4: spacetime_node.v1.GetRedemptionResponse
	(*Redemption)(nil),               // 5: spacetime_node.v1.Redemption
	(*RequestContext)(nil),           // 6: spacetime_node.v1.RequestContext
}
var file_api_proto_spacetime_node_v1_redemption_proto_depIdxs = []int32{
	6, // 0: spacetime_node.v1.CreateRedemptionRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	5, // 1: spacetime_node.v1.CreateRedemptionResponse.redemption:type_name -> spacetime_node.v1.Redemption
	6, // 2: spacetime_node.v1.GetRedemptionRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	5, // 3: spacetime_node.v1.GetRedemptionResponse.redemption:type_name -> spacetime_node.v1.Redemption
	0, // 4: spacetime_node.v1.Redemption.status:type_name -> spacetime_node.v1.RedemptionStatus
	1, // 5: spacetime_node.v1.RedemptionService.CreateRedemption:input_type -> spacetime_node.v1.CreateRedemptionRequest
	3, // 6: spacetime_node.v1.RedemptionService.GetRedemption:input_type -> spacetime_node.v1.GetRedemptionRequest
	2, // 7: spacetime_node.v1.RedemptionService.CreateRedemption:output_type -> spacetime_node.v1.CreateRedemptionResponse
	4, // 8: spacetime_node.v1.RedemptionService.GetRedemption:output_type -> spacetime_node.v1.GetRedemptionResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_redemption_proto_init() }
func file_api_proto_spacetime_node_v1_redemption_proto_init() {
	if File_api_proto_spacetime_node_v1_redemption_proto != nil {
		return
	}
	file_api_proto_spacetime_node_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_redemption_proto_rawDesc), len(file_api_proto_spacetime_node_v1_redemption_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_redemption_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_redemption_proto_depIdxs,
		EnumInfos:         file_api_proto_spacetime_node_v1_redemption_proto_enumTypes,
		MessageInfos:      file_api_proto_spacetime_node_v1_redemption_proto_msgTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_redemption_proto = out.File
	file_api_proto_spacetime_node_v1_redemption_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_redemption_proto_depIdxs = nil
}
