// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.34.1
// source: api/proto/spacetime_node/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationUserServiceGetUserProfile = "/spacetime_node.v1.UserService/GetUserProfile"
const OperationUserServiceUpdateUserPreferences = "/spacetime_node.v1.UserService/UpdateUserPreferences"

type UserServiceHTTPServer interface {
	// GetUserProfile GetUserProfile returns the demo user's profile and persisted preferences.
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	// UpdateUserPreferences UpdateUserPreferences replaces the persisted preference document.
	UpdateUserPreferences(context.Context, *UpdateUserPreferencesRequest) (*UpdateUserPreferencesResponse, error)
}

func RegisterUserServiceHTTPServer(s *http.Server, srv UserServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/users/me", _UserService_GetUserProfile0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/users/me/preferences", _UserService_UpdateUserPreferences0_HTTP_Handler(srv))
}

func _UserService_GetUserProfile0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetUserProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserProfile(ctx, req.(*GetUserProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdateUserPreferences0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserPreferencesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdateUserPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserPreferences(ctx, req.(*UpdateUserPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserPreferencesResponse)
		return ctx.Result(200, reply)
	}
}

type UserServiceHTTPClient interface {
	// GetUserProfile GetUserProfile returns the demo user's profile and persisted preferences.
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest, opts ...http.CallOption) (rsp *GetUserProfileResponse, err error)
	// UpdateUserPreferences UpdateUserPreferences replaces the persisted preference document.
	UpdateUserPreferences(ctx context.Context, req *UpdateUserPreferencesRequest, opts ...http.CallOption) (rsp *UpdateUserPreferencesResponse, err error)
}

type UserServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserServiceHTTPClient(client *http.Client) UserServiceHTTPClient {
	return &UserServiceHTTPClientImpl{client}
}

// GetUserProfile GetUserProfile returns the demo user's profile and persisted preferences.
func (c *UserServiceHTTPClientImpl) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...http.CallOption) (*GetUserProfileResponse, error) {
	var out GetUserProfileResponse
	pattern := "/v1/users/me"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationUserServiceGetUserProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserPreferences UpdateUserPreferences replaces the persisted preference document.
func (c *UserServiceHTTPClientImpl) UpdateUserPreferences(ctx context.Context, in *UpdateUserPreferencesRequest, opts ...http.CallOption) (*UpdateUserPreferencesResponse, error) {
	var out UpdateUserPreferencesResponse
	pattern := "/v1/users/me/preferences"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceUpdateUserPreferences),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
