// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/spacetime_node/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestContext *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	UserIdHash     string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *GetUserProfileRequest) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

type UpdateUserPreferencesRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RequestContext         *RequestContext        `protobuf:"bytes,1,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	UserIdHash             string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	FavoriteStationIds     []string               `protobuf:"bytes,3,rep,name=favorite_station_ids,json=favoriteStationIds,proto3" json:"favorite_station_ids,omitempty"`
	PreferredCategories    []string               `protobuf:"bytes,4,rep,name=preferred_categories,json=preferredCategories,proto3" json:"preferred_categories,omitempty"`
	BudgetMinPoints        int64                  `protobuf:"varint,5,opt,name=budget_min_points,json=budgetMinPoints,proto3" json:"budget_min_points,omitempty"`
	BudgetMaxPoints        int64                  `protobuf:"varint,6,opt,name=budget_max_points,json=budgetMaxPoints,proto3" json:"budget_max_points,omitempty"`
	Timezone               string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	NotificationsEnabled   bool                   `protobuf:"varint,8,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	NotificationStartLocal string                 `protobuf:"bytes,9,opt,name=notification_start_local,json=notificationStartLocal,proto3" json:"notification_start_local,omitempty"`
	NotificationEndLocal   string                 `protobuf:"bytes,10,opt,name=notification_end_local,json=notificationEndLocal,proto3" json:"notification_end_local,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateUserPreferencesRequest) Reset() {
	*x = UpdateUserPreferencesRequest{}
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesRequest) ProtoMessage() {}

func (x *UpdateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserPreferencesRequest) GetRequestContext() *RequestContext {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetFavoriteStationIds() []string {
	if x != nil {
		return x.FavoriteStationIds
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetPreferredCategories() []string {
	if x != nil {
		return x.PreferredCategories
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetBudgetMinPoints() int64 {
	if x != nil {
		return x.BudgetMinPoints
	}
	return 0
}

func (x *UpdateUserPreferencesRequest) GetBudgetMaxPoints() int64 {
	if x != nil {
		return x.BudgetMaxPoints
	}
	return 0
}

func (x *UpdateUserPreferencesRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *UpdateUserPreferencesRequest) GetNotificationStartLocal() string {
	if x != nil {
		return x.NotificationStartLocal
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetNotificationEndLocal() string {
	if x != nil {
		return x.NotificationEndLocal
	}
	return ""
}

type UpdateUserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferencesResponse) Reset() {
	*x = UpdateUserPreferencesResponse{}
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesResponse) ProtoMessage() {}

func (x *UpdateUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserPreferencesResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UserProfile struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserIdHash             string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	DisplayName            string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CreatedAt              string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FavoriteStationIds     []string               `protobuf:"bytes,6,rep,name=favorite_station_ids,json=favoriteStationIds,proto3" json:"favorite_station_ids,omitempty"`
	PreferredCategories    []string               `protobuf:"bytes,7,rep,name=preferred_categories,json=preferredCategories,proto3" json:"preferred_categories,omitempty"`
	BudgetMinPoints        int64                  `protobuf:"varint,8,opt,name=budget_min_points,json=budgetMinPoints,proto3" json:"budget_min_points,omitempty"`
	BudgetMaxPoints        int64                  `protobuf:"varint,9,opt,name=budget_max_points,json=budgetMaxPoints,proto3" json:"budget_max_points,omitempty"`
	Timezone               string                 `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	NotificationsEnabled   bool                   `protobuf:"varint,11,opt,name=notifications_enabled,json=notificationsEnabled,proto3" json:"notifications_enabled,omitempty"`
	NotificationStartLocal string                 `protobuf:"bytes,12,opt,name=notification_start_local,json=notificationStartLocal,proto3" json:"notification_start_local,omitempty"`
	NotificationEndLocal   string                 `protobuf:"bytes,13,opt,name=notification_end_local,json=notificationEndLocal,proto3" json:"notification_end_local,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_spacetime_node_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_spacetime_node_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserProfile) GetFavoriteStationIds() []string {
	if x != nil {
		return x.FavoriteStationIds
	}
	return nil
}

func (x *UserProfile) GetPreferredCategories() []string {
	if x != nil {
		return x.PreferredCategories
	}
	return nil
}

func (x *UserProfile) GetBudgetMinPoints() int64 {
	if x != nil {
		return x.BudgetMinPoints
	}
	return 0
}

func (x *UserProfile) GetBudgetMaxPoints() int64 {
	if x != nil {
		return x.BudgetMaxPoints
	}
	return 0
}

func (x *UserProfile) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserProfile) GetNotificationsEnabled() bool {
	if x != nil {
		return x.NotificationsEnabled
	}
	return false
}

func (x *UserProfile) GetNotificationStartLocal() string {
	if x != nil {
		return x.NotificationStartLocal
	}
	return ""
}

func (x *UserProfile) GetNotificationEndLocal() string {
	if x != nil {
		return x.NotificationEndLocal
	}
	return ""
}

var File_api_proto_spacetime_node_v1_user_proto protoreflect.FileDescriptor

const file_api_proto_spacetime_node_v1_user_proto_rawDesc = "" +
	"\n" +
	"&api/proto/spacetime_node/v1/user.proto\x12\x11spacetime_node.v1\x1a(api/proto/spacetime_node/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\x85\x01\n" +
	"\x15GetUserProfileRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\"\x8a\x04\n" +
	"\x1cUpdateUserPreferencesRequest\x12J\n" +
	"\x0frequest_context\x18\x01 \x01(\v2!.spacetime_node.v1.RequestContextR\x0erequestContext\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x120\n" +
	"\x14favorite_station_ids\x18\x03 \x03(\tR\x12favoriteStationIds\x121\n" +
	"\x14preferred_categories\x18\x04 \x03(\tR\x13preferredCategories\x12*\n" +
	"\x11budget_min_points\x18\x05 \x01(\x03R\x0fbudgetMinPoints\x12*\n" +
	"\x11budget_max_points\x18\x06 \x01(\x03R\x0fbudgetMaxPoints\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x123\n" +
	"\x15notifications_enabled\x18\b \x01(\bR\x14notificationsEnabled\x128\n" +
	"\x18notification_start_local\x18\t \x01(\tR\x16notificationStartLocal\x124\n" +
	"\x16notification_end_local\x18\n" +
	" \x01(\tR\x14notificationEndLocal\"Y\n" +
	"\x1dUpdateUserPreferencesResponse\x128\n" +
	"\aprofile\x18\x01 \x01(\v2\x1e.spacetime_node.v1.UserProfileR\aprofile\"R\n" +
	"\x16GetUserProfileResponse\x128\n" +
	"\aprofile\x18\x01 \x01(\v2\x1e.spacetime_node.v1.UserProfileR\aprofile\"\xa7\x04\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x120\n" +
	"\x14favorite_station_ids\x18\x06 \x03(\tR\x12favoriteStationIds\x121\n" +
	"\x14preferred_categories\x18\a \x03(\tR\x13preferredCategories\x12*\n" +
	"\x11budget_min_points\x18\b \x01(\x03R\x0fbudgetMinPoints\x12*\n" +
	"\x11budget_max_points\x18\t \x01(\x03R\x0fbudgetMaxPoints\x12\x1a\n" +
	"\btimezone\x18\n" +
	" \x01(\tR\btimezone\x123\n" +
	"\x15notifications_enabled\x18\v \x01(\bR\x14notificationsEnabled\x128\n" +
	"\x18notification_start_local\x18\f \x01(\tR\x16notificationStartLocal\x124\n" +
	"\x16notification_end_local\x18\r \x01(\tR\x14notificationEndLocal2\xac\x02\n" +
	"\vUserService\x12{\n" +
	"\x0eGetUserProfile\x12(.spacetime_node.v1.GetUserProfileRequest\x1a).spacetime_node.v1.GetUserProfileResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/users/me\x12\x9f\x01\n" +
	"\x15UpdateUserPreferences\x12/.spacetime_node.v1.UpdateUserPreferencesRequest\x1a0.spacetime_node.v1.UpdateUserPreferencesResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/v1/users/me/preferencesB/Z-spacetime-node/api/proto/spacetime_node/v1;v1b\x06proto3"

var (
	file_api_proto_spacetime_node_v1_user_proto_rawDescOnce sync.Once
	file_api_proto_spacetime_node_v1_user_proto_rawDescData []byte
)

func file_api_proto_spacetime_node_v1_user_proto_rawDescGZIP() []byte {
	file_api_proto_spacetime_node_v1_user_proto_rawDescOnce.Do(func() {
		file_api_proto_spacetime_node_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_user_proto_rawDesc), len(file_api_proto_spacetime_node_v1_user_proto_rawDesc)))
	})
	return file_api_proto_spacetime_node_v1_user_proto_rawDescData
}

var file_api_proto_spacetime_node_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_spacetime_node_v1_user_proto_goTypes = []any{
	(*GetUserProfileRequest)(nil),         // 0: spacetime_node.v1.GetUserProfileRequest
	(*UpdateUserPreferencesRequest)(nil),  // 1: spacetime_node.v1.UpdateUserPreferencesRequest
	(*UpdateUserPreferencesResponse)(nil), // 2: spacetime_node.v1.UpdateUserPreferencesResponse
	(*GetUserProfileResponse)(nil),        // 3: spacetime_node.v1.GetUserProfileResponse
	(*UserProfile)(nil),                   // 4: spacetime_node.v1.UserProfile
	(*RequestContext)(nil),                // 5: spacetime_node.v1.RequestContext
}
var file_api_proto_spacetime_node_v1_user_proto_depIdxs = []int32{
	5, // 0: spacetime_node.v1.GetUserProfileRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	5, // 1: spacetime_node.v1.UpdateUserPreferencesRequest.request_context:type_name -> spacetime_node.v1.RequestContext
	4, // 2: spacetime_node.v1.UpdateUserPreferencesResponse.profile:type_name -> spacetime_node.v1.UserProfile
	4, // 3: spacetime_node.v1.GetUserProfileResponse.profile:type_name -> spacetime_node.v1.UserProfile
	0, // 4: spacetime_node.v1.UserService.GetUserProfile:input_type -> spacetime_node.v1.GetUserProfileRequest
	1, // 5: spacetime_node.v1.UserService.UpdateUserPreferences:input_type -> spacetime_node.v1.UpdateUserPreferencesRequest
	3, // 6: spacetime_node.v1.UserService.GetUserProfile:output_type -> spacetime_node.v1.GetUserProfileResponse
	2, // 7: spacetime_node.v1.UserService.UpdateUserPreferences:output_type -> spacetime_node.v1.UpdateUserPreferencesResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_spacetime_node_v1_user_proto_init() }
func file_api_proto_spacetime_node_v1_user_proto_init() {
	if File_api_proto_spacetime_node_v1_user_proto != nil {
		return
	}
	file_api_proto_spacetime_node_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_spacetime_node_v1_user_proto_rawDesc), len(file_api_proto_spacetime_node_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_spacetime_node_v1_user_proto_goTypes,
		DependencyIndexes: file_api_proto_spacetime_node_v1_user_proto_depIdxs,
		MessageInfos:      file_api_proto_spacetime_node_v1_user_proto_msgTypes,
	}.Build()
	File_api_proto_spacetime_node_v1_user_proto = out.File
	file_api_proto_spacetime_node_v1_user_proto_goTypes = nil
	file_api_proto_spacetime_node_v1_user_proto_depIdxs = nil
}
